// count-lines.js — measure how much code this project actually is.
//
// The README states the project's size, and that figure has to be measured
// rather than guessed. This counts only files git tracks, splits the total the
// ways a reader actually cares about (own source vs tests vs styles and markup,
// hand-written vs generated), and says out loud what it excluded.
//
// Deliberate exclusions, all stated in the output rather than applied silently:
//   * vendor/winscp — WinSCP's own C++ source, vendored READ-ONLY as the
//     porting reference. It is not this project's code and counting it would
//     misrepresent the project by roughly 300,000 lines.
//   * node_modules, out/, dist/ — dependencies and build output, untracked.
//   * package-lock.json — a lockfile is not code.
//
// Run: node tools/count-lines.js            (human-readable table)
//      node tools/count-lines.js --markdown (the README section)
//      node tools/count-lines.js --json
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');

const ROOT = path.join(__dirname, '..');

/** Files that exist because a tool wrote them, not because a person did. */
const GENERATED = [
  'design/renderer/actions.js',    // extracted from WinSCP's NonVisual.dfm
  'design/renderer/forms.json',    // extracted from WinSCP's .dfm files
  'design/support.js',             // the design mockup's bundled runtime
  'docs/port-coverage.md',         // generated by tools/port-matrix.js
  'docs/dialog-inventory.md',      // generated by tools/extract-forms.js
];

const EXCLUDED_PREFIXES = ['vendor/'];
const EXCLUDED_FILES = ['package-lock.json'];

/**
 * Buckets, in the order they are reported. The first matching rule wins, so
 * order matters: tests are tests whatever their extension.
 */
const BUCKETS = [
  { key: 'tests', label: 'Tests', match: (p) => p.startsWith('test/') || /\.test\.js$/.test(p) },
  { key: 'main', label: 'Application — main process', match: (p) => p.startsWith('design/main/') || p.startsWith('design/preload/') },
  { key: 'renderer', label: 'Application — renderer', match: (p) => p.startsWith('design/renderer/') && /\.(js|mjs)$/.test(p) },
  { key: 'styles', label: 'Styles and markup', match: (p) => /\.(css|html|svg)$/.test(p) },
  { key: 'tools', label: 'Build and porting tools', match: (p) => p.startsWith('tools/') || p.startsWith('build/') },
  { key: 'site', label: 'Landing page and docs site', match: (p) => p.startsWith('site/') },
  { key: 'i18n', label: 'Translations and catalog data', match: (p) => /winscp-(i18n|data)\.js$/.test(p) || /\.json$/.test(p) },
  { key: 'docs', label: 'Documentation', match: (p) => /\.md$/.test(p) },
  { key: 'config', label: 'Configuration', match: () => true },
];

function trackedFiles() {
  const out = cp.execFileSync('git', ['ls-files'], { cwd: ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  return out.split('\n').map((s) => s.trim()).filter(Boolean);
}

function isBinary(rel) {
  return /\.(png|jpg|jpeg|gif|ico|webp|zip|exe|nupkg|woff2?|ttf|otf|pdf)$/i.test(rel);
}

function countFile(rel) {
  const abs = path.join(ROOT, rel);
  let buf;
  try { buf = fs.readFileSync(abs); } catch { return null; }
  // A NUL byte means this is not text, whatever its extension claims.
  if (buf.includes(0)) return null;
  const text = buf.toString('utf8');
  const lines = text.split('\n');
  // A trailing newline produces a final empty element that is not a line.
  if (lines.length && lines[lines.length - 1] === '') lines.pop();
  const total = lines.length;
  let nonBlank = 0;
  for (const l of lines) if (l.trim()) nonBlank++;
  return { total, nonBlank };
}

function measure() {
  const excluded = { vendored: { files: 0 }, binary: { files: 0 }, lockfile: { files: 0 } };
  const buckets = new Map(BUCKETS.map((b) => [b.key, { ...b, files: 0, total: 0, nonBlank: 0 }]));
  const generated = { files: 0, total: 0, nonBlank: 0 };

  for (const rel of trackedFiles()) {
    if (EXCLUDED_PREFIXES.some((p) => rel.startsWith(p))) { excluded.vendored.files++; continue; }
    if (EXCLUDED_FILES.includes(rel)) { excluded.lockfile.files++; continue; }
    if (isBinary(rel)) { excluded.binary.files++; continue; }

    const c = countFile(rel);
    if (!c) { excluded.binary.files++; continue; }

    if (GENERATED.includes(rel)) {
      generated.files++; generated.total += c.total; generated.nonBlank += c.nonBlank;
      continue;
    }
    const b = buckets.get(BUCKETS.find((x) => x.match(rel)).key);
    b.files++; b.total += c.total; b.nonBlank += c.nonBlank;
  }

  const rows = [...buckets.values()].filter((b) => b.files > 0);
  const handTotal = rows.reduce((a, b) => a + b.total, 0);
  const handNonBlank = rows.reduce((a, b) => a + b.nonBlank, 0);

  return {
    rows, generated, excluded,
    handWritten: { total: handTotal, nonBlank: handNonBlank, files: rows.reduce((a, b) => a + b.files, 0) },
    grand: { total: handTotal + generated.total, nonBlank: handNonBlank + generated.nonBlank },
    commit: (() => {
      try { return cp.execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim(); }
      catch { return 'unknown'; }
    })(),
    date: new Date().toISOString().slice(0, 10),
  };
}

function vendoredReference() {
  // Reported separately so a reader can see the scale of what is being ported
  // without it ever being folded into this project's own figure.
  const dir = path.join(ROOT, 'vendor', 'winscp', 'source');
  if (!fs.existsSync(dir)) return null;
  let total = 0, files = 0;
  const stack = [dir];
  while (stack.length) {
    const d = stack.pop();
    let items;
    try { items = fs.readdirSync(d, { withFileTypes: true }); } catch { continue; }
    for (const it of items) {
      const p = path.join(d, it.name);
      if (it.isDirectory()) { stack.push(p); continue; }
      if (!/\.(cpp|h|c|dfm|rc)$/i.test(it.name)) continue;
      const c = countFile(path.relative(ROOT, p));
      if (c) { total += c.total; files++; }
    }
  }
  return { total, files };
}

const n = (x) => x.toLocaleString('en-US');

function markdown(m, ref) {
  const L = [];
  L.push('| Part | Files | Lines | Non-blank |');
  L.push('|---|---:|---:|---:|');
  for (const r of m.rows) L.push(`| ${r.label} | ${n(r.files)} | ${n(r.total)} | ${n(r.nonBlank)} |`);
  L.push(`| **Hand-written total** | **${n(m.handWritten.files)}** | **${n(m.handWritten.total)}** | **${n(m.handWritten.nonBlank)}** |`);
  if (m.generated.files) {
    L.push(`| Generated (extracted from WinSCP's own definitions) | ${n(m.generated.files)} | ${n(m.generated.total)} | ${n(m.generated.nonBlank)} |`);
    L.push(`| **Total including generated** | | **${n(m.grand.total)}** | **${n(m.grand.nonBlank)}** |`);
  }
  L.push('');
  L.push('**Excluded, deliberately:**');
  L.push('');
  L.push(`- \`vendor/winscp\` — ${ref ? n(ref.total) + ' lines of' : ''} WinSCP's own C++ source, vendored read-only as the porting reference. It is not this project's code.`);
  L.push('- `node_modules`, `out/`, `dist/` — dependencies and build output (untracked).');
  L.push('- `package-lock.json` — a lockfile is not code.');
  L.push('- Binary assets (images, icons, fonts).');
  L.push('');
  L.push(`Measured over \`git ls-files\` at commit \`${m.commit}\` on ${m.date}. Reproduce with:`);
  L.push('');
  L.push('```bash');
  L.push('node tools/count-lines.js');
  L.push('```');
  return L.join('\n');
}

function main() {
  const m = measure();
  const ref = vendoredReference();

  if (process.argv.includes('--json')) {
    console.log(JSON.stringify({ ...m, vendoredReference: ref }, null, 2));
    return;
  }
  if (process.argv.includes('--markdown')) {
    console.log(markdown(m, ref));
    return;
  }

  const w = Math.max(...m.rows.map((r) => r.label.length), 20);
  console.log('This project:');
  for (const r of m.rows) {
    console.log(`  ${r.label.padEnd(w)}  ${String(n(r.files)).padStart(5)} files  ${String(n(r.total)).padStart(8)} lines  ${String(n(r.nonBlank)).padStart(8)} non-blank`);
  }
  console.log(`  ${'HAND-WRITTEN TOTAL'.padEnd(w)}  ${String(n(m.handWritten.files)).padStart(5)} files  ${String(n(m.handWritten.total)).padStart(8)} lines  ${String(n(m.handWritten.nonBlank)).padStart(8)} non-blank`);
  if (m.generated.files) {
    console.log(`  ${'generated (extracted)'.padEnd(w)}  ${String(n(m.generated.files)).padStart(5)} files  ${String(n(m.generated.total)).padStart(8)} lines  ${String(n(m.generated.nonBlank)).padStart(8)} non-blank`);
    console.log(`  ${'TOTAL incl. generated'.padEnd(w)}  ${' '.repeat(5)}        ${String(n(m.grand.total)).padStart(8)} lines  ${String(n(m.grand.nonBlank)).padStart(8)} non-blank`);
  }
  console.log('\nExcluded:');
  console.log(`  vendor/winscp        ${n(m.excluded.vendored.files)} files` + (ref ? `  (${n(ref.total)} lines of WinSCP's own C++ — the porting reference, not our code)` : ''));
  console.log(`  binary assets        ${n(m.excluded.binary.files)} files`);
  console.log(`  lockfile             ${n(m.excluded.lockfile.files)} file`);
  console.log(`\nMeasured over \`git ls-files\` at commit ${m.commit} on ${m.date}.`);
}

if (require.main === module) main();
module.exports = { measure, vendoredReference, markdown };
